generator: admingenerator.generator.doctrine
params:
    model: Vtsot\CmsBundle\Entity\Page
    namespace_prefix: Vtsot
    concurrency_lock: ~
    bundle_name: CmsBundle
    pk_requirement: ~
    fields:
        id:     { label: "ID" }
        name:   { label: "Название" }
        rank:   { label: "Сортировка" }
        swSite: { label: "Отображение на сайте" }
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title:      "Список страниц"
            display:    [ id, name, rank, swSite ]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display:    [ id, name, swSite ]
    new:
        params:
            title:      "Добавить страницу"
            display:
                "Page Data":    [ url, name, description ]
                "Meta Data":    [ metaTitle, metaKeywords, metaDescription ]
                "Display Data": [ rank, swSite ]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title:      "Редактировать страницу \"%object%\"|{ %object%: Page.name }|"
            display:
                "Item Data":    [ url, name, description ]
                "Meta Data":    [ metaTitle, metaKeywords, metaDescription ]
                "Display Data": [ rank, swSite ]
            actions:
                save: ~
                list: ~
    show:
        params:
            title:      "Данные страницы \"%object%\"|{ %object%: Page.name }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
