cms_main_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CmsMainBundle:Default:index }

CmsMainBundlePage:
    resource: "@CmsMainBundle/Controller/Page/"
    type:     admingenerator
    prefix:   /page
